# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NativeModulePlayground' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativeModulePlayground
  
  pod 'OptimizelySDKiOS','2.1.0'


  target 'NativeModulePlayground-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NativeModulePlaygroundTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
